# Generated by Django 3.2.7 on 2021-10-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQLaORM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizard',
            old_name='qyear',
            new_name='year',
        ),
    ]
