# Generated by Django 3.2.7 on 2021-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
