# Generated by Django 3.2.7 on 2021-10-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores', '0002_alter_books_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
    ]
